### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vovkasm**
Update dev deps to latest versions.
And most important, update tern to v0.20.0 (current)

### CODE REVIEW

**Comment by jacksonrayhamilton** [comment]
Thanks for doing this. However, is there a particular reason for bumping the package versions?

**Comment by vovkasm** [comment]
Yes. Probably just aestetic ;-)
When I install tern-jsx to atom-ternjs directory this warning happens:

``` sh
atom-ternjs@0.15.0 /Users/vovkasm/work/atom-ternjs
├── UNMET PEER DEPENDENCY tern@0.20.0
└── tern-jsx@1.0.1

npm WARN tern-jsx@1.0.1 requires a peer of tern@^0.19.0 but none was installed.
```

Then, when I clone tern-jsx itself and `npm install`:

``` sh
vovkasm@vovkasm-macbook> npm install                                                                                                                                                                                                                                          ~/work/tern-jsx
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
...
```

Upgrade resolve these warnings.

**Comment by jacksonrayhamilton** [comment]
Makes sense. Could you undo the indentation changes in the ESLint configuration, update the comment at the top to say "Configured for ESLint 3.4.0," and exchange the `no-native-reassign` and `no-negated-in-lhs` rules for the `no-global-assign` and `no-unsafe-negation` rules, respectively, while preserving the alphabetical order of the rules? After that, it should be good to go.

**Comment by vovkasm** [comment]
Good, will do it in near 24h

**Comment by jacksonrayhamilton** [comment]
Thank you!

**Pull request merged**
